name: Run Python Script Twice Daily

on:
  schedule:
    - cron: '0 6,18 * * *'  # Runs at 06:00 and 18:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies (if needed)
        run: |
          pip install -r requirements.txt || echo "No dependencies to install"

      - name: Run Python Script with Secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          INVERTER_SN: ${{ secrets.INVERTER_SN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python script.py
